name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get commit ID
      run: echo "$(git rev-parse --short HEAD)""
    - name: Build
      run: docker build . --tag saifeequazii/capitalbetting
