name: CICD

on:
  push:
    branches: [ "main-patch" ]
  pull_request:
    branches: [ "main-patch" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get commit ID
      run: echo "$(git rev-parse --short HEAD)" >tag
      
